version: '3.1'
services:
  db:
    image: mysql
    container_name: gerenciador
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - matsu_data:/var/lib/gc/mysql

volumes:
  matsu_data: